Sprint 2/step 2
at-90/react-burger pull request #4
Opened 2023-05-27 06:46 UTC by at-90

2023-05-27 07:12 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Раздельное хранение булок и ингредиентов в хранилище конструктора
- Редьюсеры - чистые функции
- Хорошая организация хранилища

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- если экшен не выполняет сайдэффектов, то не должна диспатчится функция и пропускатсья через `thunk`
- В запросе на номер заказа вы передаете объекты ингредиентов, а нужно только строки айдишников.

<img width="1440" alt="Снимок экрана 2023-05-27 в 10 06 41" src="https://github.com/at-90/react-burger/assets/60173362/78a17ea5-bf8a-4648-8f55-32929cd48a08">

- Контекст на данном этапе уже следует заменить на `redux` 

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-27 07:12 UTC, andryxxa93 commented on src/services/actions/burger-constructor.js
> +    return (dispatch) => {
**Надо исправить**

не совсем верно организован диспатчи простых экшенов, не требующих сайд эффектов.

Если действие не требует запросов к серверу или каких то побочных эффектов, то нужно дисптчить просто объект экшена, а не функцию

Например, как сделано сейчас:

Описана функция

```
export const moveConstructorItem = (dragIndex, hoverIndex) => (dispatch) => {
	dispatch({
		type: MOVE_CONSTRUCTOR_ITEM,
		dragIndex,
		hoverIndex,
	});
};

dispatch(moveConstructorItem(dragIndex, hoverIndex)); //будет задиспатчена функция
```

Если присмотреться, то в коде есть два dispatch. Что при этом происходит:

мы диспатчик функцию => thunk перехватывает функцию => thunk выполняет функцию => функция сама диспатчит экшен => экшен попадает в редьюсер

В случае экшена не требующего сайдэффектов 2, 3 и 4 звено в цепочке лишние, т.к. не нужно пропускать простые экшены через thunk

Как должно быть:

```
//такая функция называется action creator - она принимает данные и возвращает объект (а не функцию)
export const moveConstructorItem = (dragIndex, hoverIndex) => ({
	type: MOVE_CONSTRUCTOR_ITEM,
	dragIndex,
	hoverIndex,
});

dispatch(moveConstructorItem(dragIndex, hoverIndex));
```

Но в этом случае будет задиспатчен объект
при этом не будет в цепочке обработки экшена лишних шагов, экшен не будет перехвачен thunk т.к. является объектом, а не функцией, а попадет сразу в редюсер

Нужно исправить это замечание для всех подобных мест в проекте, где при диспатче нужно просто передать экшен в редьюсер, а не выполнять сайдэффекты.

2023-05-27 07:12 UTC, andryxxa93 commented on src/components/ingredients-list/ingredients-list.jsx
> +    const { buns, components } = useSelector(store => store.burgerConstructor);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-05-27 07:12 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const buns = items.filter(elem => elem.type === 'bun');
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-05-27 07:12 UTC, andryxxa93 commented on src/components/ingredients-list/ingredients-list.jsx
> +    })
**Можно лучше**
Такие операции лучше помещать в `useEffect` или `useMemo`- иначе они будут выполняться каждый рендер

2023-05-28 11:39 UTC, at-90 commented on src/services/actions/burger-constructor.js
> +    return (dispatch) => {
Сделано. Проверил все вызовы dispatch в компонентах

2023-05-28 11:41 UTC, at-90 commented on src/components/ingredients-list/ingredients-list.jsx
> +    const { buns, components } = useSelector(store => store.burgerConstructor);
Переделал во всех компонентах. Кажется, такие функции называются селекторы.
Пример из видео сложноват :) Но, изучу детальнее

2023-05-28 11:41 UTC, at-90 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const buns = items.filter(elem => elem.type === 'bun');
Сделано

2023-05-28 11:43 UTC, at-90 commented on src/components/ingredients-list/ingredients-list.jsx
> +    })
Сделал. До этого почти не использовал useMemo, считал, что такие операции а ниших небольших компонентах лишняя нагрузка. Как переоптимизация

2023-05-28 11:45 UTC, at-90 commented
Все замечания устранил. Также те, что "можно лучше". Очистку конструктора,  сделал на закрытие модального окна, а не в методе then. Думаю так логичнее

2023-05-28 19:07 UTC, andryxxa93 commented on src/components/ingredients-list/ingredients-list.jsx
> +    const { buns, components } = useSelector(store => store.burgerConstructor);
Да, всё правильно они называются селекторы )

2023-05-28 19:10 UTC, andryxxa93 commented on src/components/ingredients-list/ingredients-list.jsx
> +    })
На этот счёт есть много споров - нужно ли использовать `useMemo` или нет. Чаще всего никакого прироста производительности от таких точечных внедрений `useMemo` вы не заметите, однако в больших приложениях - это может принести пользу при достижении какой-то критической массы. Обычно по поводу использования `useMemo` договориваются внутри команды, но привычку лучше воспитывать уже сейчас )

2023-05-28 19:14 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-29 16:36 UTC, merged